name: Bug report
description: Report something that is broken or incorrect
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please read the guide on [writing a good bug report](https://matthewrocklin.com/minimal-bug-reports).
        Include the following in your description:

        - Steps to reproduce in a clean Python environment
        - Details about your data (or use a publicly available dataset)

  - type: textarea
    id: report
    attributes:
      label: Report
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Version information
      description: |
        Run `python -c "import session_info; session_info.show()"` and paste the output here.
        If you don't have session-info2 installed, run `pip install session-info2` first.
      placeholder: |
        -----
        anndata             0.11.3
        numpy               2.2.2
        peach               0.3.0
        scanpy              1.10.4
        scipy               1.15.1
        -----
        Python 3.11.0 | packaged by conda-forge
        Linux-6.5.0
    validations:
      required: true
